name: Ubuntu C/C++ CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install depedensity
      run: 
          sudo apt install cmake gcc g++ git
    - name: cmake configure
      run: 
          cmake -S . -B _build
    - name: cmake build
      run: 
          cmake --build _build -j8    
