name: Ubuntu C/C++ CI


on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install depedensity
      run: |
        sudo apt install cmake gcc g++ git
    - name: cmake configure
      run: |
        cmake -S . -B _build
    - name: cmake build
      run: |
        cmake --build _build -j8
    - name: Create hash
      run: |
        sha256sum _build/bin/dtv/dtv-cli > _build/bin/dtv/dtv-cli.txt

    - uses: softprops/action-gh-release@v2
      with:
        files: |
          _build/bin/dtv/dtv-cli
          _build/bin/dtv/dtv-cli.txt
